
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Calc;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int _SYMB_5 = 7;
  public static final int _SYMB_4 = 6;
  public static final int _SYMB_3 = 5;
  public static final int _SYMB_2 = 4;
  public static final int _SYMB_1 = 3;
  public static final int _SYMB_0 = 2;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int _INTEGER_ = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "_SYMB_0",
  "_SYMB_1",
  "_SYMB_2",
  "_SYMB_3",
  "_SYMB_4",
  "_SYMB_5",
  "_INTEGER_"
  };
}

