package sample.Absyn; // Java Package generated by the BNF Converter.

public class AnonymFunc extends Expr {
  public final FArgs fargs_;
  public final Program program_;
  public final Type type_;
  public AnonymFunc(FArgs p1, Program p2, Type p3) { fargs_ = p1; program_ = p2; type_ = p3; }

  public <R,A> R accept(sample.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof sample.Absyn.AnonymFunc) {
      sample.Absyn.AnonymFunc x = (sample.Absyn.AnonymFunc)o;
      return this.fargs_.equals(x.fargs_) && this.program_.equals(x.program_) && this.type_.equals(x.type_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.fargs_.hashCode())+this.program_.hashCode())+this.type_.hashCode();
  }


}
