package Sample.Absyn; // Java Package generated by the BNF Converter.

public abstract class Assignment_op implements java.io.Serializable {
  public abstract <R,A> R accept(Assignment_op.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(Sample.Absyn.Assign p, A arg);

  }

}
