package Sample.Absyn; // Java Package generated by the BNF Converter.

public class Assign extends Assignment_op {
  public Assign() { }

  public <R,A> R accept(Sample.Absyn.Assignment_op.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Sample.Absyn.Assign) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
