package Sample.Absyn; // Java Package generated by the BNF Converter.

public abstract class BindingExpr implements java.io.Serializable {
  public abstract <R,A> R accept(BindingExpr.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(Sample.Absyn.Binding p, A arg);

  }

}
