package Sample.Absyn; // Java Package generated by the BNF Converter.

public class Builtin extends Expr {
  public final BuiltinCall builtincall_;
  public Builtin(BuiltinCall p1) { builtincall_ = p1; }

  public <R,A> R accept(Sample.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Sample.Absyn.Builtin) {
      Sample.Absyn.Builtin x = (Sample.Absyn.Builtin)o;
      return this.builtincall_.equals(x.builtincall_);
    }
    return false;
  }

  public int hashCode() {
    return this.builtincall_.hashCode();
  }


}
