package Sample.Absyn; // Java Package generated by the BNF Converter.

public abstract class BuiltinCall implements java.io.Serializable {
  public abstract <R,A> R accept(BuiltinCall.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(Sample.Absyn.Not p, A arg);
    public R visit(Sample.Absyn.And p, A arg);
    public R visit(Sample.Absyn.Or p, A arg);

  }

}
