// File generated by the BNF Converter (bnfc 2.9.4).

package sample.Absyn;

public abstract class Dec implements java.io.Serializable {
  public abstract <R,A> R accept(Dec.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(sample.Absyn.Declaration p, A arg);
    public R visit(sample.Absyn.LcVarDeclaration p, A arg);

  }

}
