// File generated by the BNF Converter (bnfc 2.9.4).

package sample.Absyn;

public class EDouble  extends Expr {
  public final Double double_;
  public EDouble(Double p1) { double_ = p1; }

  public <R,A> R accept(sample.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof sample.Absyn.EDouble) {
      sample.Absyn.EDouble x = (sample.Absyn.EDouble)o;
      return this.double_.equals(x.double_);
    }
    return false;
  }

  public int hashCode() {
    return this.double_.hashCode();
  }


}
