// File generated by the BNF Converter (bnfc 2.9.4).

package sample.Absyn;

public class EStr  extends Expr {
  public final String string_;
  public EStr(String p1) { string_ = p1; }

  public <R,A> R accept(sample.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof sample.Absyn.EStr) {
      sample.Absyn.EStr x = (sample.Absyn.EStr)o;
      return this.string_.equals(x.string_);
    }
    return false;
  }

  public int hashCode() {
    return this.string_.hashCode();
  }


}
