package Sample.Absyn; // Java Package generated by the BNF Converter.

public class EStr extends Expr {
  public final String string_;
  public EStr(String p1) { string_ = p1; }

  public <R,A> R accept(Sample.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Sample.Absyn.EStr) {
      Sample.Absyn.EStr x = (Sample.Absyn.EStr)o;
      return this.string_.equals(x.string_);
    }
    return false;
  }

  public int hashCode() {
    return this.string_.hashCode();
  }


}
