package Sample.Absyn; // Java Package generated by the BNF Converter.

public abstract class Expr implements java.io.Serializable {
  public abstract <R,A> R accept(Expr.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(Sample.Absyn.Var p, A arg);
    public R visit(Sample.Absyn.ConstTrue p, A arg);
    public R visit(Sample.Absyn.ConstFalse p, A arg);
    public R visit(Sample.Absyn.If p, A arg);
    public R visit(Sample.Absyn.EInt p, A arg);
    public R visit(Sample.Absyn.EDouble p, A arg);
    public R visit(Sample.Absyn.EStr p, A arg);
    public R visit(Sample.Absyn.Not p, A arg);
    public R visit(Sample.Absyn.And p, A arg);
    public R visit(Sample.Absyn.Or p, A arg);
    public R visit(Sample.Absyn.ConstZero p, A arg);
    public R visit(Sample.Absyn.Succ p, A arg);
    public R visit(Sample.Absyn.Pred p, A arg);
    public R visit(Sample.Absyn.IsZero p, A arg);
    public R visit(Sample.Absyn.OnlyDecl p, A arg);
    public R visit(Sample.Absyn.InitDecl p, A arg);

  }

}
