// File generated by the BNF Converter (bnfc 2.9.4).

package sample.Absyn;

public abstract class FArgs implements java.io.Serializable {
  public abstract <R,A> R accept(FArgs.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(sample.Absyn.FuncArgs p, A arg);

  }

}
