package sample.Absyn; // Java Package generated by the BNF Converter.

public abstract class Fields implements java.io.Serializable {
  public abstract <R,A> R accept(Fields.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(sample.Absyn.LBFields p, A arg);

  }

}
