// File generated by the BNF Converter (bnfc 2.9.4).

package sample.Absyn;

public class Func  extends Expr {
  public final String ident_;
  public final FArgs fargs_;
  public final Type type_;
  public final Program program_;
  public Func(String p1, FArgs p2, Type p3, Program p4) { ident_ = p1; fargs_ = p2; type_ = p3; program_ = p4; }

  public <R,A> R accept(sample.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof sample.Absyn.Func) {
      sample.Absyn.Func x = (sample.Absyn.Func)o;
      return this.ident_.equals(x.ident_) && this.fargs_.equals(x.fargs_) && this.type_.equals(x.type_) && this.program_.equals(x.program_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(37*(this.ident_.hashCode())+this.fargs_.hashCode())+this.type_.hashCode())+this.program_.hashCode();
  }


}
