package Sample.Absyn; // Java Package generated by the BNF Converter.

public class FuncArgs extends FArgs {
  public final ListDec listdec_;
  public FuncArgs(ListDec p1) { listdec_ = p1; }

  public <R,A> R accept(Sample.Absyn.FArgs.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Sample.Absyn.FuncArgs) {
      Sample.Absyn.FuncArgs x = (Sample.Absyn.FuncArgs)o;
      return this.listdec_.equals(x.listdec_);
    }
    return false;
  }

  public int hashCode() {
    return this.listdec_.hashCode();
  }


}
