package Sample.Absyn; // Java Package generated by the BNF Converter.

public class FuncTypeAnnotation extends Expr {
  public final String ident_;
  public final FArgs fargs_;
  public final TAnnot tannot_;
  public final Program program_;
  public FuncTypeAnnotation(String p1, FArgs p2, TAnnot p3, Program p4) { ident_ = p1; fargs_ = p2; tannot_ = p3; program_ = p4; }

  public <R,A> R accept(Sample.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Sample.Absyn.FuncTypeAnnotation) {
      Sample.Absyn.FuncTypeAnnotation x = (Sample.Absyn.FuncTypeAnnotation)o;
      return this.ident_.equals(x.ident_) && this.fargs_.equals(x.fargs_) && this.tannot_.equals(x.tannot_) && this.program_.equals(x.program_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(37*(this.ident_.hashCode())+this.fargs_.hashCode())+this.tannot_.hashCode())+this.program_.hashCode();
  }


}
