package Sample.Absyn; // Java Package generated by the BNF Converter.

public class FuncTypeAscription extends Expr {
  public final String ident_;
  public final FArgs fargs_;
  public final TAscript tascript_;
  public final Program program_;
  public FuncTypeAscription(String p1, FArgs p2, TAscript p3, Program p4) { ident_ = p1; fargs_ = p2; tascript_ = p3; program_ = p4; }

  public <R,A> R accept(Sample.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Sample.Absyn.FuncTypeAscription) {
      Sample.Absyn.FuncTypeAscription x = (Sample.Absyn.FuncTypeAscription)o;
      return this.ident_.equals(x.ident_) && this.fargs_.equals(x.fargs_) && this.tascript_.equals(x.tascript_) && this.program_.equals(x.program_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(37*(this.ident_.hashCode())+this.fargs_.hashCode())+this.tascript_.hashCode())+this.program_.hashCode();
  }


}
