package Sample.Absyn; // Java Package generated by the BNF Converter.

public abstract class Funct implements java.io.Serializable {
  public abstract <R,A> R accept(Funct.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(Sample.Absyn.Func p, A arg);

  }

}
