package sample.Absyn; // Java Package generated by the BNF Converter.

public class FuncType extends Type {
  public final FArgs fargs_;
  public final Type type_;
  public FuncType(FArgs p1, Type p2) { fargs_ = p1; type_ = p2; }

  public <R,A> R accept(sample.Absyn.Type.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof sample.Absyn.FuncType) {
      sample.Absyn.FuncType x = (sample.Absyn.FuncType)o;
      return this.fargs_.equals(x.fargs_) && this.type_.equals(x.type_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.fargs_.hashCode())+this.type_.hashCode();
  }


}
