package sample.Absyn; // Java Package generated by the BNF Converter.

public class GlTableDecl extends Expr {
  public final Dec dec_;
  public final String ident_1, ident_2;
  public GlTableDecl(Dec p1, String p2, String p3) { dec_ = p1; ident_1 = p2; ident_2 = p3; }

  public <R,A> R accept(sample.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof sample.Absyn.GlTableDecl) {
      sample.Absyn.GlTableDecl x = (sample.Absyn.GlTableDecl)o;
      return this.dec_.equals(x.dec_) && this.ident_1.equals(x.ident_1) && this.ident_2.equals(x.ident_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.dec_.hashCode())+this.ident_1.hashCode())+this.ident_2.hashCode();
  }


}
