package sample.Absyn; // Java Package generated by the BNF Converter.

public class Idents extends Idts {
  public final ListIdent listident_;
  public Idents(ListIdent p1) { listident_ = p1; }

  public <R,A> R accept(sample.Absyn.Idts.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof sample.Absyn.Idents) {
      sample.Absyn.Idents x = (sample.Absyn.Idents)o;
      return this.listident_.equals(x.listident_);
    }
    return false;
  }

  public int hashCode() {
    return this.listident_.hashCode();
  }


}
