package sample.Absyn; // Java Package generated by the BNF Converter.

public class If extends Expr {
  public final Expr expr_;
  public final Program program_1, program_2;
  public If(Expr p1, Program p2, Program p3) { expr_ = p1; program_1 = p2; program_2 = p3; }

  public <R,A> R accept(sample.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof sample.Absyn.If) {
      sample.Absyn.If x = (sample.Absyn.If)o;
      return this.expr_.equals(x.expr_) && this.program_1.equals(x.program_1) && this.program_2.equals(x.program_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.expr_.hashCode())+this.program_1.hashCode())+this.program_2.hashCode();
  }


}
