package sample.Absyn; // Java Package generated by the BNF Converter.

public class Import extends Expr {
  public final String ident_;
  public Import(String p1) { ident_ = p1; }

  public <R,A> R accept(sample.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof sample.Absyn.Import) {
      sample.Absyn.Import x = (sample.Absyn.Import)o;
      return this.ident_.equals(x.ident_);
    }
    return false;
  }

  public int hashCode() {
    return this.ident_.hashCode();
  }


}
