package Sample.Absyn; // Java Package generated by the BNF Converter.

public abstract class Init_declarator implements java.io.Serializable {
  public abstract <R,A> R accept(Init_declarator.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(Sample.Absyn.OnlyDecl p, A arg);
    public R visit(Sample.Absyn.InitDecl p, A arg);

  }

}
