// File generated by the BNF Converter (bnfc 2.9.4).

package sample.Absyn;

public class InitDecl  extends Expr {
  public final Dec dec_;
  public final Expr expr_;
  public InitDecl(Dec p1, Expr p2) { dec_ = p1; expr_ = p2; }

  public <R,A> R accept(sample.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof sample.Absyn.InitDecl) {
      sample.Absyn.InitDecl x = (sample.Absyn.InitDecl)o;
      return this.dec_.equals(x.dec_) && this.expr_.equals(x.expr_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.dec_.hashCode())+this.expr_.hashCode();
  }


}
