package sample.Absyn; // Java Package generated by the BNF Converter.

public class InitGlDecl extends Expr {
  public final GlDec gldec_;
  public final Expr expr_;
  public InitGlDecl(GlDec p1, Expr p2) { gldec_ = p1; expr_ = p2; }

  public <R,A> R accept(sample.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof sample.Absyn.InitGlDecl) {
      sample.Absyn.InitGlDecl x = (sample.Absyn.InitGlDecl)o;
      return this.gldec_.equals(x.gldec_) && this.expr_.equals(x.expr_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.gldec_.hashCode())+this.expr_.hashCode();
  }


}
