package sample.Absyn; // Java Package generated by the BNF Converter.

public class InitGlTableDecl extends Expr {
  public final GlDec gldec_;
  public final Dec dec_1, dec_2;
  public InitGlTableDecl(GlDec p1, Dec p2, Dec p3) { gldec_ = p1; dec_1 = p2; dec_2 = p3; }

  public <R,A> R accept(sample.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof sample.Absyn.InitGlTableDecl) {
      sample.Absyn.InitGlTableDecl x = (sample.Absyn.InitGlTableDecl)o;
      return this.gldec_.equals(x.gldec_) && this.dec_1.equals(x.dec_1) && this.dec_2.equals(x.dec_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.gldec_.hashCode())+this.dec_1.hashCode())+this.dec_2.hashCode();
  }


}
