// File generated by the BNF Converter (bnfc 2.9.4).

package sample.Absyn;

public class LcTypeAliasing  extends Expr {
  public final String ident_;
  public final TypeKW typekw_;
  public final Type type_;
  public LcTypeAliasing(String p1, TypeKW p2, Type p3) { ident_ = p1; typekw_ = p2; type_ = p3; }

  public <R,A> R accept(sample.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof sample.Absyn.LcTypeAliasing) {
      sample.Absyn.LcTypeAliasing x = (sample.Absyn.LcTypeAliasing)o;
      return this.ident_.equals(x.ident_) && this.typekw_.equals(x.typekw_) && this.type_.equals(x.type_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.ident_.hashCode())+this.typekw_.hashCode())+this.type_.hashCode();
  }


}
