// File generated by the BNF Converter (bnfc 2.9.4).

package sample.Absyn;

public class LcVarTypeAnnotation  extends Expr {
  public final String ident_;
  public final TAnnot tannot_;
  public final Expr expr_;
  public LcVarTypeAnnotation(String p1, TAnnot p2, Expr p3) { ident_ = p1; tannot_ = p2; expr_ = p3; }

  public <R,A> R accept(sample.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof sample.Absyn.LcVarTypeAnnotation) {
      sample.Absyn.LcVarTypeAnnotation x = (sample.Absyn.LcVarTypeAnnotation)o;
      return this.ident_.equals(x.ident_) && this.tannot_.equals(x.tannot_) && this.expr_.equals(x.expr_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.ident_.hashCode())+this.tannot_.hashCode())+this.expr_.hashCode();
  }


}
