package sample.Absyn; // Java Package generated by the BNF Converter.

public class LetBinding extends Expr {
  public final Fields fields_;
  public final Expr expr_;
  public LetBinding(Fields p1, Expr p2) { fields_ = p1; expr_ = p2; }

  public <R,A> R accept(sample.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof sample.Absyn.LetBinding) {
      sample.Absyn.LetBinding x = (sample.Absyn.LetBinding)o;
      return this.fields_.equals(x.fields_) && this.expr_.equals(x.expr_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.fields_.hashCode())+this.expr_.hashCode();
  }


}
