package sample.Absyn; // Java Package generated by the BNF Converter.

public class OnlyGlDecl extends Expr {
  public final GlDec gldec_;
  public OnlyGlDecl(GlDec p1) { gldec_ = p1; }

  public <R,A> R accept(sample.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof sample.Absyn.OnlyGlDecl) {
      sample.Absyn.OnlyGlDecl x = (sample.Absyn.OnlyGlDecl)o;
      return this.gldec_.equals(x.gldec_);
    }
    return false;
  }

  public int hashCode() {
    return this.gldec_.hashCode();
  }


}
