package Sample.Absyn; // Java Package generated by the BNF Converter.

public class Return extends Expr {
  public final Expr expr_;
  public Return(Expr p1) { expr_ = p1; }

  public <R,A> R accept(Sample.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Sample.Absyn.Return) {
      Sample.Absyn.Return x = (Sample.Absyn.Return)o;
      return this.expr_.equals(x.expr_);
    }
    return false;
  }

  public int hashCode() {
    return this.expr_.hashCode();
  }


}
