package Sample.Absyn; // Java Package generated by the BNF Converter.

public abstract class TAliasing implements java.io.Serializable {
  public abstract <R,A> R accept(TAliasing.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(Sample.Absyn.TypeAliasing p, A arg);

  }

}
