// File generated by the BNF Converter (bnfc 2.9.4).

package sample.Absyn;

public abstract class TAscript implements java.io.Serializable {
  public abstract <R,A> R accept(TAscript.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(sample.Absyn.TypeAscription p, A arg);

  }

}
