package Sample.Absyn; // Java Package generated by the BNF Converter.

public abstract class TAscript implements java.io.Serializable {
  public abstract <R,A> R accept(TAscript.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(Sample.Absyn.TypeAscription p, A arg);

  }

}
