package Sample.Absyn; // Java Package generated by the BNF Converter.

public abstract class Type_specifier implements java.io.Serializable {
  public abstract <R,A> R accept(Type_specifier.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(Sample.Absyn.Tint p, A arg);

  }

}
