package sample.Absyn; // Java Package generated by the BNF Converter.

public class TypeAnField extends Field {
  public final String ident_;
  public final VarKW varkw_;
  public final Expr expr_;
  public TypeAnField(String p1, VarKW p2, Expr p3) { ident_ = p1; varkw_ = p2; expr_ = p3; }

  public <R,A> R accept(sample.Absyn.Field.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof sample.Absyn.TypeAnField) {
      sample.Absyn.TypeAnField x = (sample.Absyn.TypeAnField)o;
      return this.ident_.equals(x.ident_) && this.varkw_.equals(x.varkw_) && this.expr_.equals(x.expr_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.ident_.hashCode())+this.varkw_.hashCode())+this.expr_.hashCode();
  }


}
