package Sample.Absyn; // Java Package generated by the BNF Converter.

public class TypeAliasing extends Expr {
  public final String ident_;
  public final TypeKW typekw_;
  public final Type type_;
  public TypeAliasing(String p1, TypeKW p2, Type p3) { ident_ = p1; typekw_ = p2; type_ = p3; }

  public <R,A> R accept(Sample.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Sample.Absyn.TypeAliasing) {
      Sample.Absyn.TypeAliasing x = (Sample.Absyn.TypeAliasing)o;
      return this.ident_.equals(x.ident_) && this.typekw_.equals(x.typekw_) && this.type_.equals(x.type_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.ident_.hashCode())+this.typekw_.hashCode())+this.type_.hashCode();
  }


}
