package sample.Absyn; // Java Package generated by the BNF Converter.

public class TypeAlAnonymFunc extends Expr {
  public final FArgs fargs_;
  public final Program program_;
  public final String ident_;
  public TypeAlAnonymFunc(FArgs p1, Program p2, String p3) { fargs_ = p1; program_ = p2; ident_ = p3; }

  public <R,A> R accept(sample.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof sample.Absyn.TypeAlAnonymFunc) {
      sample.Absyn.TypeAlAnonymFunc x = (sample.Absyn.TypeAlAnonymFunc)o;
      return this.fargs_.equals(x.fargs_) && this.program_.equals(x.program_) && this.ident_.equals(x.ident_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.fargs_.hashCode())+this.program_.hashCode())+this.ident_.hashCode();
  }


}
