package sample.Absyn; // Java Package generated by the BNF Converter.

public class TypeAlDecl extends Dec {
  public final String ident_1, ident_2;
  public TypeAlDecl(String p1, String p2) { ident_1 = p1; ident_2 = p2; }

  public <R,A> R accept(sample.Absyn.Dec.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof sample.Absyn.TypeAlDecl) {
      sample.Absyn.TypeAlDecl x = (sample.Absyn.TypeAlDecl)o;
      return this.ident_1.equals(x.ident_1) && this.ident_2.equals(x.ident_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.ident_1.hashCode())+this.ident_2.hashCode();
  }


}
