// File generated by the BNF Converter (bnfc 2.9.4).

package sample.Absyn;

public class TypeAnnotation  extends TAnnot {
  public final VarKW varkw_;
  public TypeAnnotation(VarKW p1) { varkw_ = p1; }

  public <R,A> R accept(sample.Absyn.TAnnot.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof sample.Absyn.TypeAnnotation) {
      sample.Absyn.TypeAnnotation x = (sample.Absyn.TypeAnnotation)o;
      return this.varkw_.equals(x.varkw_);
    }
    return false;
  }

  public int hashCode() {
    return this.varkw_.hashCode();
  }


}
