package Sample.Absyn; // Java Package generated by the BNF Converter.

public class TypeAnnotation extends TAnnot {
  public final VarKW varkw_;
  public TypeAnnotation(VarKW p1) { varkw_ = p1; }

  public <R,A> R accept(Sample.Absyn.TAnnot.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Sample.Absyn.TypeAnnotation) {
      Sample.Absyn.TypeAnnotation x = (Sample.Absyn.TypeAnnotation)o;
      return this.varkw_.equals(x.varkw_);
    }
    return false;
  }

  public int hashCode() {
    return this.varkw_.hashCode();
  }


}
