package Sample.Absyn; // Java Package generated by the BNF Converter.

public class TypeAscription extends TAscript {
  public final TAnnot tannot_;
  public final Type type_;
  public TypeAscription(TAnnot p1, Type p2) { tannot_ = p1; type_ = p2; }

  public <R,A> R accept(Sample.Absyn.TAscript.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Sample.Absyn.TypeAscription) {
      Sample.Absyn.TypeAscription x = (Sample.Absyn.TypeAscription)o;
      return this.tannot_.equals(x.tannot_) && this.type_.equals(x.type_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.tannot_.hashCode())+this.type_.hashCode();
  }


}
