package sample.Absyn; // Java Package generated by the BNF Converter.

public class TypeAlFunc extends Expr {
  public final String ident_1, ident_2;
  public final FArgs fargs_;
  public final Program program_;
  public TypeAlFunc(String p1, FArgs p2, String p3, Program p4) { ident_1 = p1; fargs_ = p2; ident_2 = p3; program_ = p4; }

  public <R,A> R accept(sample.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof sample.Absyn.TypeAlFunc) {
      sample.Absyn.TypeAlFunc x = (sample.Absyn.TypeAlFunc)o;
      return this.ident_1.equals(x.ident_1) && this.fargs_.equals(x.fargs_) && this.ident_2.equals(x.ident_2) && this.program_.equals(x.program_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(37*(this.ident_1.hashCode())+this.fargs_.hashCode())+this.ident_2.hashCode())+this.program_.hashCode();
  }


}
