package sample.Absyn; // Java Package generated by the BNF Converter.

public abstract class Type implements java.io.Serializable {
  public abstract <R,A> R accept(Type.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(sample.Absyn.StringType p, A arg);
    public R visit(sample.Absyn.BoolType p, A arg);
    public R visit(sample.Absyn.IntType p, A arg);
    public R visit(sample.Absyn.DoubleType p, A arg);
    public R visit(sample.Absyn.TableType p, A arg);
    public R visit(sample.Absyn.VoidType p, A arg);

  }

}
