package Sample.Absyn; // Java Package generated by the BNF Converter.

public class TypingStmt extends Typing {
  public final Expr expr_;
  public final Type type_;
  public TypingStmt(Expr p1, Type p2) { expr_ = p1; type_ = p2; }

  public <R,A> R accept(Sample.Absyn.Typing.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Sample.Absyn.TypingStmt) {
      Sample.Absyn.TypingStmt x = (Sample.Absyn.TypingStmt)o;
      return this.expr_.equals(x.expr_) && this.type_.equals(x.type_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.expr_.hashCode())+this.type_.hashCode();
  }


}
