package Sample.Absyn; // Java Package generated by the BNF Converter.

public abstract class Typing implements java.io.Serializable {
  public abstract <R,A> R accept(Typing.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(Sample.Absyn.TypingStmt p, A arg);

  }

}
