package sample.Absyn; // Java Package generated by the BNF Converter.

public abstract class VarKW implements java.io.Serializable {
  public abstract <R,A> R accept(VarKW.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(sample.Absyn.VarKeyword p, A arg);

  }

}
