package Sample.Absyn; // Java Package generated by the BNF Converter.

public class Vars extends ComaExprs {
  public final ListExpr listexpr_;
  public Vars(ListExpr p1) { listexpr_ = p1; }

  public <R,A> R accept(Sample.Absyn.ComaExprs.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Sample.Absyn.Vars) {
      Sample.Absyn.Vars x = (Sample.Absyn.Vars)o;
      return this.listexpr_.equals(x.listexpr_);
    }
    return false;
  }

  public int hashCode() {
    return this.listexpr_.hashCode();
  }


}
