package Sample.Absyn; // Java Package generated by the BNF Converter.

public class Vary extends Expr {
  public final String ident_;
  public Vary(String p1) { ident_ = p1; }

  public <R,A> R accept(Sample.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Sample.Absyn.Vary) {
      Sample.Absyn.Vary x = (Sample.Absyn.Vary)o;
      return this.ident_.equals(x.ident_);
    }
    return false;
  }

  public int hashCode() {
    return this.ident_.hashCode();
  }


}
