// File generated by the BNF Converter (bnfc 2.9.4).

package syntax.nameless.Absyn;

public class BoundVar  extends Expr {
  public final Integer integer_;
  public BoundVar(Integer p1) { integer_ = p1; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof BoundVar) {
      BoundVar x = (BoundVar)o;
      return this.integer_.equals(x.integer_);
    }
    return false;
  }

  public int hashCode() {
    return this.integer_.hashCode();
  }


}
