// File generated by the BNF Converter (bnfc 2.9.4).

package syntax.nameless.Absyn;

public abstract class Expr implements java.io.Serializable {
  public abstract <R,A> R accept(Expr.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(ConstTrue p, A arg);
    public R visit(ConstFalse p, A arg);
    public R visit(If p, A arg);
    public R visit(ConstZero p, A arg);
    public R visit(Succ p, A arg);
    public R visit(Pred p, A arg);
    public R visit(IsZero p, A arg);
    public R visit(FreeVar p, A arg);
    public R visit(BoundVar p, A arg);
    public R visit(Abstraction p, A arg);
    public R visit(Application p, A arg);

  }

}
