// File generated by the BNF Converter (bnfc 2.9.4).

package syntax.nameless;

import syntax.nameless.Absyn.Expr.Visitor;

/** All Visitor */

public interface AllVisitor<R,A> extends
  Visitor<R,A>
{}
