// File generated by the BNF Converter (bnfc 2.9.4).

package syntax.nameless;

import syntax.nameless.Absyn.*;

public class PrettyPrinter
{
  //For certain applications increasing the initial size of the buffer may improve performance.
  private static final int INITIAL_BUFFER_SIZE = 128;
  private static final int INDENT_WIDTH = 2;
  //You may wish to change the parentheses used in precedence.
  private static final String _L_PAREN = new String("(");
  private static final String _R_PAREN = new String(")");
  //You may wish to change render
  private static void render(String s)
  {
    if (s.equals("{"))
    {
       onEmptyLine();
       buf_.append(s);
       _n_ = _n_ + INDENT_WIDTH;
       buf_.append("\n");
       indent();
    }
    else if (s.equals("(") || s.equals("["))
       buf_.append(s);
    else if (s.equals(")") || s.equals("]"))
    {
       removeTrailingWhitespace();
       buf_.append(s);
       buf_.append(" ");
    }
    else if (s.equals("}"))
    {
       _n_ = _n_ - INDENT_WIDTH;
       onEmptyLine();
       buf_.append(s);
       buf_.append("\n");
       indent();
    }
    else if (s.equals(","))
    {
       removeTrailingWhitespace();
       buf_.append(s);
       buf_.append(" ");
    }
    else if (s.equals(";"))
    {
       removeTrailingWhitespace();
       buf_.append(s);
       buf_.append("\n");
       indent();
    }
    else if (s.equals("")) return;
    else if (s.trim().equals(""))
    {
       backup();
       buf_.append(s);
    }
    else
    {
       buf_.append(s);
       buf_.append(" ");
    }
  }


  //  print and show methods are defined for each category.
  public static String print(Expr foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(Expr foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  /***   You shouldn't need to change anything beyond this point.   ***/

  private static void pp(Expr foo, int _i_)
  {
    if (foo instanceof ConstTrue)
    {
       ConstTrue _consttrue = (ConstTrue) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("true");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof ConstFalse)
    {
       ConstFalse _constfalse = (ConstFalse) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("false");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof If)
    {
       If _if = (If) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("if");
       pp(_if.expr_1, 0);
       render("then");
       pp(_if.expr_2, 0);
       render("else");
       pp(_if.expr_3, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof ConstZero)
    {
       ConstZero _constzero = (ConstZero) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("0");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof Succ)
    {
       Succ _succ = (Succ) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("succ");
       pp(_succ.expr_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof Pred)
    {
       Pred _pred = (Pred) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("pred");
       pp(_pred.expr_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof IsZero)
    {
       IsZero _iszero = (IsZero) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("iszero");
       pp(_iszero.expr_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof FreeVar)
    {
       FreeVar _freevar = (FreeVar) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_freevar.ident_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof BoundVar)
    {
       BoundVar _boundvar = (BoundVar) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("[");
       pp(_boundvar.integer_, 0);
       render("]");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof Abstraction)
    {
       Abstraction _abstraction = (Abstraction) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("fun");
       render("{");
       render("return");
       pp(_abstraction.expr_, 0);
       render("}");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof Application)
    {
       Application _application = (Application) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_application.expr_1, 0);
       pp(_application.expr_2, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }


  private static void sh(Expr foo)
  {
    if (foo instanceof ConstTrue)
    {
       ConstTrue _consttrue = (ConstTrue) foo;
       render("ConstTrue");
    }
    if (foo instanceof ConstFalse)
    {
       ConstFalse _constfalse = (ConstFalse) foo;
       render("ConstFalse");
    }
    if (foo instanceof If)
    {
       If _if = (If) foo;
       render("(");
       render("If");
       sh(_if.expr_1);
       sh(_if.expr_2);
       sh(_if.expr_3);
       render(")");
    }
    if (foo instanceof ConstZero)
    {
       ConstZero _constzero = (ConstZero) foo;
       render("ConstZero");
    }
    if (foo instanceof Succ)
    {
       Succ _succ = (Succ) foo;
       render("(");
       render("Succ");
       sh(_succ.expr_);
       render(")");
    }
    if (foo instanceof Pred)
    {
       Pred _pred = (Pred) foo;
       render("(");
       render("Pred");
       sh(_pred.expr_);
       render(")");
    }
    if (foo instanceof IsZero)
    {
       IsZero _iszero = (IsZero) foo;
       render("(");
       render("IsZero");
       sh(_iszero.expr_);
       render(")");
    }
    if (foo instanceof FreeVar)
    {
       FreeVar _freevar = (FreeVar) foo;
       render("(");
       render("FreeVar");
       sh(_freevar.ident_);
       render(")");
    }
    if (foo instanceof BoundVar)
    {
       BoundVar _boundvar = (BoundVar) foo;
       render("(");
       render("BoundVar");
       sh(_boundvar.integer_);
       render(")");
    }
    if (foo instanceof Abstraction)
    {
       Abstraction _abstraction = (Abstraction) foo;
       render("(");
       render("Abstraction");
       sh(_abstraction.expr_);
       render(")");
    }
    if (foo instanceof Application)
    {
       Application _application = (Application) foo;
       render("(");
       render("Application");
       sh(_application.expr_1);
       sh(_application.expr_2);
       render(")");
    }
  }


  private static void pp(Integer n, int _i_) { buf_.append(n); buf_.append(" "); }
  private static void pp(Double d, int _i_) { buf_.append(String.format(java.util.Locale.ROOT, "%.15g ", d)); }
  private static void pp(String s, int _i_) { buf_.append(s); buf_.append(" "); }
  private static void pp(Character c, int _i_) { buf_.append("'" + c.toString() + "'"); buf_.append(" "); }
  private static void sh(Integer n) { render(n.toString()); }
  private static void sh(Double d) { render(String.format(java.util.Locale.ROOT, "%.15g", d)); }
  private static void sh(Character c) { render("'" + c.toString() + "'"); }
  private static void sh(String s) { printQuoted(s); }

  private static void printQuoted(String s) { render("\"" + s + "\""); }

  private static void indent()
  {
    int n = _n_;
    while (n > 0)
    {
      buf_.append(' ');
      n--;
    }
  }

  private static void backup()
  {
    int prev = buf_.length() - 1;
    if (prev >= 0 && buf_.charAt(prev) == ' ')
      buf_.setLength(prev);
  }

  private static void trim()
  {
    // Trim initial spaces
    int end = 0;
    int len = buf_.length();
    while (end < len && buf_.charAt(end) == ' ')
      end++;
    buf_.delete(0, end);
    // Trim trailing spaces
    removeTrailingSpaces();
  }

  private static void removeTrailingSpaces()
  {
    int end = buf_.length();
    while (end > 0 && buf_.charAt(end-1) == ' ')
      end--;
    buf_.setLength(end);
  }

  private static void removeTrailingWhitespace()
  {
    int end = buf_.length();
    while (end > 0 && (buf_.charAt(end-1) == ' ' || buf_.charAt(end-1) == '\n'))
      end--;
    buf_.setLength(end);
  }

  private static void onEmptyLine()
  {
    removeTrailingSpaces();
    int len = buf_.length();
    if (len > 0 && buf_.charAt(len-1) != '\n') buf_.append("\n");
    indent();
  }

  private static int _n_ = 0;
  private static StringBuilder buf_ = new StringBuilder(INITIAL_BUFFER_SIZE);
}

