package Sample.Absyn; // Java Package generated by the BNF Converter.

public abstract class FieldTypeExpr implements java.io.Serializable {
  public abstract <R,A> R accept(FieldTypeExpr.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(Sample.Absyn.FieldType p, A arg);

  }

}
